[package]
name = "evie-core"
version.workspace = true
edition.workspace = true

[dependencies]
arc-swap = "1.7"
dashmap = "6.1"
ropey = { workspace = true }
thiserror = "2.0"
tokio = { workspace = true }
